<?php

namespace Modules\SettingModule\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class SettingModuleDatabaseSeeder extends Seeder
{
    public function run(): void
    {
        Model::unguard();

        DB::table('countries')->truncate();

        // [name, name_ar, code, phone_code, currency]
        $rows = [
            ['Afghanistan', 'أفغانستان', 'AF', '+93', 'AFN'],
            ['Albania', 'ألبانيا', 'AL', '+355', 'ALL'],
            ['Algeria', 'الجزائر', 'DZ', '+213', 'DZD'],
            ['Andorra', 'أندورا', 'AD', '+376', 'EUR'],
            ['Angola', 'أنغولا', 'AO', '+244', 'AOA'],
            ['Antigua and Barbuda', 'أنتيغوا وبربودا', 'AG', '+1-268', 'XCD'],
            ['Argentina', 'الأرجنتين', 'AR', '+54', 'ARS'],
            ['Armenia', 'أرمينيا', 'AM', '+374', 'AMD'],
            ['Australia', 'أستراليا', 'AU', '+61', 'AUD'],
            ['Austria', 'النمسا', 'AT', '+43', 'EUR'],
            ['Azerbaijan', 'أذربيجان', 'AZ', '+994', 'AZN'],
            ['Bahamas', 'جزر البهاما', 'BS', '+1-242', 'BSD'],
            ['Bahrain', 'البحرين', 'BH', '+973', 'BHD'],
            ['Bangladesh', 'بنغلاديش', 'BD', '+880', 'BDT'],
            ['Barbados', 'بربادوس', 'BB', '+1-246', 'BBD'],
            ['Belarus', 'بيلاروسيا', 'BY', '+375', 'BYN'],
            ['Belgium', 'بلجيكا', 'BE', '+32', 'EUR'],
            ['Belize', 'بليز', 'BZ', '+501', 'BZD'],
            ['Benin', 'بنين', 'BJ', '+229', 'XOF'],
            ['Bhutan', 'بوتان', 'BT', '+975', 'BTN'],
            ['Bolivia', 'بوليفيا', 'BO', '+591', 'BOB'],
            ['Bosnia and Herzegovina', 'البوسنة والهرسك', 'BA', '+387', 'BAM'],
            ['Botswana', 'بوتسوانا', 'BW', '+267', 'BWP'],
            ['Brazil', 'البرازيل', 'BR', '+55', 'BRL'],
            ['Brunei', 'بروناي', 'BN', '+673', 'BND'],
            ['Bulgaria', 'بلغاريا', 'BG', '+359', 'BGN'],
            ['Burkina Faso', 'بوركينا فاسو', 'BF', '+226', 'XOF'],
            ['Burundi', 'بوروندي', 'BI', '+257', 'BIF'],
            ['Cabo Verde', 'الرأس الأخضر', 'CV', '+238', 'CVE'],
            ['Cambodia', 'كمبوديا', 'KH', '+855', 'KHR'],
            ['Cameroon', 'الكاميرون', 'CM', '+237', 'XAF'],
            ['Canada', 'كندا', 'CA', '+1', 'CAD'],
            ['Central African Republic', 'جمهورية أفريقيا الوسطى', 'CF', '+236', 'XAF'],
            ['Chad', 'تشاد', 'TD', '+235', 'XAF'],
            ['Chile', 'تشيلي', 'CL', '+56', 'CLP'],
            ['China', 'الصين', 'CN', '+86', 'CNY'],
            ['Colombia', 'كولومبيا', 'CO', '+57', 'COP'],
            ['Comoros', 'جزر القمر', 'KM', '+269', 'KMF'],
            ['Congo', 'الكونغو', 'CG', '+242', 'XAF'],
            ['Congo (DRC)', 'جمهورية الكونغو الديمقراطية', 'CD', '+243', 'CDF'],
            ['Costa Rica', 'كوستاريكا', 'CR', '+506', 'CRC'],
            ['Croatia', 'كرواتيا', 'HR', '+385', 'EUR'],
            ['Cuba', 'كوبا', 'CU', '+53', 'CUP'],
            ['Cyprus', 'قبرص', 'CY', '+357', 'EUR'],
            ['Czech Republic', 'جمهورية التشيك', 'CZ', '+420', 'CZK'],
            ['Denmark', 'الدنمارك', 'DK', '+45', 'DKK'],
            ['Djibouti', 'جيبوتي', 'DJ', '+253', 'DJF'],
            ['Dominica', 'دومينيكا', 'DM', '+1-767', 'XCD'],
            ['Dominican Republic', 'جمهورية الدومينيكان', 'DO', '+1-809', 'DOP'],
            ['Ecuador', 'الإكوادور', 'EC', '+593', 'USD'],
            ['Egypt', 'مصر', 'EG', '+20', 'EGP'],
            ['El Salvador', 'السلفادور', 'SV', '+503', 'USD'],
            ['Equatorial Guinea', 'غينيا الاستوائية', 'GQ', '+240', 'XAF'],
            ['Eritrea', 'إريتريا', 'ER', '+291', 'ERN'],
            ['Estonia', 'إستونيا', 'EE', '+372', 'EUR'],
            ['Eswatini', 'إسواتيني', 'SZ', '+268', 'SZL'],
            ['Ethiopia', 'إثيوبيا', 'ET', '+251', 'ETB'],
            ['Fiji', 'فيجي', 'FJ', '+679', 'FJD'],
            ['Finland', 'فنلندا', 'FI', '+358', 'EUR'],
            ['France', 'فرنسا', 'FR', '+33', 'EUR'],
            ['Gabon', 'الغابون', 'GA', '+241', 'XAF'],
            ['Gambia', 'غامبيا', 'GM', '+220', 'GMD'],
            ['Georgia', 'جورجيا', 'GE', '+995', 'GEL'],
            ['Germany', 'ألمانيا', 'DE', '+49', 'EUR'],
            ['Ghana', 'غانا', 'GH', '+233', 'GHS'],
            ['Greece', 'اليونان', 'GR', '+30', 'EUR'],
            ['Grenada', 'غرينادا', 'GD', '+1-473', 'XCD'],
            ['Guatemala', 'غواتيمالا', 'GT', '+502', 'GTQ'],
            ['Guinea', 'غينيا', 'GN', '+224', 'GNF'],
            ['Guinea-Bissau', 'غينيا بيساو', 'GW', '+245', 'XOF'],
            ['Guyana', 'غيانا', 'GY', '+592', 'GYD'],
            ['Haiti', 'هايتي', 'HT', '+509', 'HTG'],
            ['Honduras', 'هندوراس', 'HN', '+504', 'HNL'],
            ['Hungary', 'المجر', 'HU', '+36', 'HUF'],
            ['Iceland', 'أيسلندا', 'IS', '+354', 'ISK'],
            ['India', 'الهند', 'IN', '+91', 'INR'],
            ['Indonesia', 'إندونيسيا', 'ID', '+62', 'IDR'],
            ['Iran', 'إيران', 'IR', '+98', 'IRR'],
            ['Iraq', 'العراق', 'IQ', '+964', 'IQD'],
            ['Ireland', 'أيرلندا', 'IE', '+353', 'EUR'],
            ['Israel', 'إسرائيل', 'IL', '+972', 'ILS'],
            ['Italy', 'إيطاليا', 'IT', '+39', 'EUR'],
            ['Ivory Coast', 'ساحل العاج', 'CI', '+225', 'XOF'],
            ['Jamaica', 'جامايكا', 'JM', '+1-876', 'JMD'],
            ['Japan', 'اليابان', 'JP', '+81', 'JPY'],
            ['Jordan', 'الأردن', 'JO', '+962', 'JOD'],
            ['Kazakhstan', 'كازاخستان', 'KZ', '+7', 'KZT'],
            ['Kenya', 'كينيا', 'KE', '+254', 'KES'],
            ['Kiribati', 'كيريباتي', 'KI', '+686', 'AUD'],
            ['Kuwait', 'الكويت', 'KW', '+965', 'KWD'],
            ['Kyrgyzstan', 'قيرغيزستان', 'KG', '+996', 'KGS'],
            ['Laos', 'لاوس', 'LA', '+856', 'LAK'],
            ['Latvia', 'لاتفيا', 'LV', '+371', 'EUR'],
            ['Lebanon', 'لبنان', 'LB', '+961', 'LBP'],
            ['Lesotho', 'ليسوتو', 'LS', '+266', 'LSL'],
            ['Liberia', 'ليبيريا', 'LR', '+231', 'LRD'],
            ['Libya', 'ليبيا', 'LY', '+218', 'LYD'],
            ['Liechtenstein', 'ليختنشتاين', 'LI', '+423', 'CHF'],
            ['Lithuania', 'ليتوانيا', 'LT', '+370', 'EUR'],
            ['Luxembourg', 'لوكسمبورغ', 'LU', '+352', 'EUR'],
            ['Madagascar', 'مدغشقر', 'MG', '+261', 'MGA'],
            ['Malawi', 'مالاوي', 'MW', '+265', 'MWK'],
            ['Malaysia', 'ماليزيا', 'MY', '+60', 'MYR'],
            ['Maldives', 'جزر المالديف', 'MV', '+960', 'MVR'],
            ['Mali', 'مالي', 'ML', '+223', 'XOF'],
            ['Malta', 'مالطا', 'MT', '+356', 'EUR'],
            ['Marshall Islands', 'جزر مارشال', 'MH', '+692', 'USD'],
            ['Mauritania', 'موريتانيا', 'MR', '+222', 'MRU'],
            ['Mauritius', 'موريشيوس', 'MU', '+230', 'MUR'],
            ['Mexico', 'المكسيك', 'MX', '+52', 'MXN'],
            ['Micronesia', 'ميكرونيزيا', 'FM', '+691', 'USD'],
            ['Moldova', 'مولدوفا', 'MD', '+373', 'MDL'],
            ['Monaco', 'موناكو', 'MC', '+377', 'EUR'],
            ['Mongolia', 'منغوليا', 'MN', '+976', 'MNT'],
            ['Montenegro', 'الجبل الأسود', 'ME', '+382', 'EUR'],
            ['Morocco', 'المغرب', 'MA', '+212', 'MAD'],
            ['Mozambique', 'موزمبيق', 'MZ', '+258', 'MZN'],
            ['Myanmar', 'ميانمار', 'MM', '+95', 'MMK'],
            ['Namibia', 'ناميبيا', 'NA', '+264', 'NAD'],
            ['Nauru', 'ناورو', 'NR', '+674', 'AUD'],
            ['Nepal', 'نيبال', 'NP', '+977', 'NPR'],
            ['Netherlands', 'هولندا', 'NL', '+31', 'EUR'],
            ['New Zealand', 'نيوزيلندا', 'NZ', '+64', 'NZD'],
            ['Nicaragua', 'نيكاراغوا', 'NI', '+505', 'NIO'],
            ['Niger', 'النيجر', 'NE', '+227', 'XOF'],
            ['Nigeria', 'نيجيريا', 'NG', '+234', 'NGN'],
            ['North Korea', 'كوريا الشمالية', 'KP', '+850', 'KPW'],
            ['North Macedonia', 'مقدونيا الشمالية', 'MK', '+389', 'MKD'],
            ['Norway', 'النرويج', 'NO', '+47', 'NOK'],
            ['Oman', 'عُمان', 'OM', '+968', 'OMR'],
            ['Pakistan', 'باكستان', 'PK', '+92', 'PKR'],
            ['Palau', 'بالاو', 'PW', '+680', 'USD'],
            ['Palestine', 'فلسطين', 'PS', '+970', 'ILS'],
            ['Panama', 'بنما', 'PA', '+507', 'PAB'],
            ['Papua New Guinea', 'بابوا غينيا الجديدة', 'PG', '+675', 'PGK'],
            ['Paraguay', 'باراغواي', 'PY', '+595', 'PYG'],
            ['Peru', 'بيرو', 'PE', '+51', 'PEN'],
            ['Philippines', 'الفلبين', 'PH', '+63', 'PHP'],
            ['Poland', 'بولندا', 'PL', '+48', 'PLN'],
            ['Portugal', 'البرتغال', 'PT', '+351', 'EUR'],
            ['Qatar', 'قطر', 'QA', '+974', 'QAR'],
            ['Romania', 'رومانيا', 'RO', '+40', 'RON'],
            ['Russia', 'روسيا', 'RU', '+7', 'RUB'],
            ['Rwanda', 'رواندا', 'RW', '+250', 'RWF'],
            ['Saint Kitts and Nevis', 'سانت كيتس ونيفيس', 'KN', '+1-869', 'XCD'],
            ['Saint Lucia', 'سانت لوسيا', 'LC', '+1-758', 'XCD'],
            ['Saint Vincent and the Grenadines', 'سانت فنسنت وجزر غرينادين', 'VC', '+1-784', 'XCD'],
            ['Samoa', 'ساموا', 'WS', '+685', 'WST'],
            ['San Marino', 'سان مارينو', 'SM', '+378', 'EUR'],
            ['Sao Tome and Principe', 'ساو تومي وبرينسيبي', 'ST', '+239', 'STN'],
            ['Saudi Arabia', 'المملكة العربية السعودية', 'SA', '+966', 'SAR'],
            ['Senegal', 'السنغال', 'SN', '+221', 'XOF'],
            ['Serbia', 'صربيا', 'RS', '+381', 'RSD'],
            ['Seychelles', 'سيشل', 'SC', '+248', 'SCR'],
            ['Sierra Leone', 'سيراليون', 'SL', '+232', 'SLL'],
            ['Singapore', 'سنغافورة', 'SG', '+65', 'SGD'],
            ['Slovakia', 'سلوفاكيا', 'SK', '+421', 'EUR'],
            ['Slovenia', 'سلوفينيا', 'SI', '+386', 'EUR'],
            ['Solomon Islands', 'جزر سليمان', 'SB', '+677', 'SBD'],
            ['Somalia', 'الصومال', 'SO', '+252', 'SOS'],
            ['South Africa', 'جنوب أفريقيا', 'ZA', '+27', 'ZAR'],
            ['South Korea', 'كوريا الجنوبية', 'KR', '+82', 'KRW'],
            ['South Sudan', 'جنوب السودان', 'SS', '+211', 'SSP'],
            ['Spain', 'إسبانيا', 'ES', '+34', 'EUR'],
            ['Sri Lanka', 'سريلانكا', 'LK', '+94', 'LKR'],
            ['Sudan', 'السودان', 'SD', '+249', 'SDG'],
            ['Suriname', 'سورينام', 'SR', '+597', 'SRD'],
            ['Sweden', 'السويد', 'SE', '+46', 'SEK'],
            ['Switzerland', 'سويسرا', 'CH', '+41', 'CHF'],
            ['Syria', 'سوريا', 'SY', '+963', 'SYP'],
            ['Taiwan', 'تايوان', 'TW', '+886', 'TWD'],
            ['Tajikistan', 'طاجيكستان', 'TJ', '+992', 'TJS'],
            ['Tanzania', 'تنزانيا', 'TZ', '+255', 'TZS'],
            ['Thailand', 'تايلاند', 'TH', '+66', 'THB'],
            ['Timor-Leste', 'تيمور الشرقية', 'TL', '+670', 'USD'],
            ['Togo', 'توغو', 'TG', '+228', 'XOF'],
            ['Tonga', 'تونغا', 'TO', '+676', 'TOP'],
            ['Trinidad and Tobago', 'ترينيداد وتوباغو', 'TT', '+1-868', 'TTD'],
            ['Tunisia', 'تونس', 'TN', '+216', 'TND'],
            ['Turkey', 'تركيا', 'TR', '+90', 'TRY'],
            ['Turkmenistan', 'تركمانستان', 'TM', '+993', 'TMT'],
            ['Tuvalu', 'توفالو', 'TV', '+688', 'AUD'],
            ['Uganda', 'أوغندا', 'UG', '+256', 'UGX'],
            ['Ukraine', 'أوكرانيا', 'UA', '+380', 'UAH'],
            ['United Arab Emirates', 'الإمارات العربية المتحدة', 'AE', '+971', 'AED'],
            ['United Kingdom', 'المملكة المتحدة', 'GB', '+44', 'GBP'],
            ['United States', 'الولايات المتحدة الأمريكية', 'US', '+1', 'USD'],
            ['Uruguay', 'أوروغواي', 'UY', '+598', 'UYU'],
            ['Uzbekistan', 'أوزبكستان', 'UZ', '+998', 'UZS'],
            ['Vanuatu', 'فانواتو', 'VU', '+678', 'VUV'],
            ['Vatican City', 'الفاتيكان', 'VA', '+379', 'EUR'],
            ['Venezuela', 'فنزويلا', 'VE', '+58', 'VES'],
            ['Vietnam', 'فيتنام', 'VN', '+84', 'VND'],
            ['Yemen', 'اليمن', 'YE', '+967', 'YER'],
            ['Zambia', 'زامبيا', 'ZM', '+260', 'ZMW'],
            ['Zimbabwe', 'زيمبابوي', 'ZW', '+263', 'ZWL'],
        ];

        $countries = array_map(function ($r, $index) {
            return [
                'name'       => $r[0],
                'name_ar'    => $r[1],
                'code'       => strtolower($r[2]),
                'flag'       => strtolower($r[2]),
                'phone_code' => $r[3],
                'currency'   => $r[4],
                'sort_order' => $this->countrySortOrder($r[0], $index),
            ];
        }, $rows, array_keys($rows));

        DB::table('countries')->insert($countries);
    }

    private function countrySortOrder(string $countryName, int $index): int
    {
        $gulfCountries = ['Bahrain', 'Oman', 'Qatar', 'Saudi Arabia', 'United Arab Emirates'];
        $arabicCountries = [
            'Algeria',
            'Comoros',
            'Djibouti',
            'Egypt',
            'Iraq',
            'Jordan',
            'Lebanon',
            'Libya',
            'Mauritania',
            'Morocco',
            'Palestine',
            'Somalia',
            'Sudan',
            'Syria',
            'Tunisia',
            'Yemen',
        ];

        if ($countryName === 'Kuwait') {
            return 1;
        }

        if (in_array($countryName, $gulfCountries, true)) {
            return 2 + array_search($countryName, $gulfCountries, true);
        }

        if (in_array($countryName, $arabicCountries, true)) {
            return 7 + array_search($countryName, $arabicCountries, true);
        }

        return 1000 + $index;
    }
}
